### PR TITLE
Path.expand before Path.wildcard for Windows

### PR DESCRIPTION
**Pull request by simonmcconnell**
Hello friends.  Thanks for doing the hard yards!

This PR sneaks `Path.expand` in before any `Path.wildcard` so it can be used on Windows.

Are there any other blockers for Windows builds?  I've shoehorned a soon-to-be-released project I've been working on that generates an executable instead of all the batch scripts and allows extra CLI commands.  That felt easier than figuring out passing/escaping args, which I know you have enjoyed playing with!  I'm able to build my project, but it uses a custom build pipeline, no wrapping.  Happy to help with Windows nightmares.

### CODE REVIEW

**Comment by ashea-code** [comment]
First, thanks for the PR! It's always appreciated -- I'll try and review/merge this soon!

As far as Windows build support goes, we simply haven't written the alternative commands (for example we use `which` to determine if a command exists in the user's path, and I'm sure there's a few other spots where we rely on more POSIX conventions, so those will have to be searched out and replaced with an alternative Windows backend at runtime. The new build flow refactor probably helps in this regard.

**Comment by simonmcconnell** [comment]
Righto, I can look into that.  I tend to `scoop install coreutils` which puts all that stuff in my path, so that's probably why it worked for me.

**Comment by simonmcconnell** [comment]
@ashea-code can we merge this?  I'd like to submit some more PRs but doing anything with Burrito on Windows depends on this.

**Comment by doawoo** [comment]
Sorry about the delay, this looks good!

**Pull request merged**
